### ISSUE TITLE
Borderless buttons missing ripple

### ISSUE THREAD

**Issue by L3K0V** [L3K0V/aesthetic#1]

**Comment by tcqq** [comment]
Regarding the ripple does not show the problem, I found that in: 
```
* Dark theme = true
* Primary color = BLACK
* Accent color = PURPLE
```
or
```
* Dark theme = true
* Primary color = WHITE
* Accent color = BLUE
```
or
```
* Dark theme = false
* Primary color = RED
* Accent color = YELLOW
```
the ripple will be displayed,

---

in: 
```
* Dark theme = false
* Primary color = BLACK
* Accent color = PURPLE
```
or
```
* Dark theme = false
* Primary color = WHITE
* Accent color = BLUE
```
or
```
* Dark theme = true
* Primary color = RED
* Accent color = YELLOW
```
the ripple will not be displayed.


The ripple are have two colors, one suitable for displaying on a dark background and one suitable for displaying on a light background, So the problem of ripples not showing should be related to the color.

**Comment by L3K0V** [comment]
@tcqq you can validate it now, borderless button should be rippled now with the background colour of the buttons.

**Comment by tcqq** [comment]
Thank you.
